import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "./globals.css";

const be_Vietnam_Pro = Be_Vietnam_Pro({ subsets: ["latin"], weight: ["300"] });

export const metadata: Metadata = {
  title: "AlphaTrue",
  description: "Generated by AlphaTrue",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={(be_Vietnam_Pro.className, "bg-body")}>
        <NextTopLoader showSpinner={false} color="#00B6DD" />
        <main className="bg-secondBody">
          <div className="w-full h-fit bg-body rounded-b-3xl relative z-10">
            <Header />
            <div className="px-3 lg:px-10">{children}</div>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
